trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      test
    steps:
    - task: Docker@2
      displayName: 'Build the Docker image'
      inputs:
        command: 'build'
        dockerfile: '$(Build.SourcesDirectory)/exerciseoftheday/Dockerfile'
        imageName: 'sudiptod/image1'
        includeLatestTag: true
        tags: |
          $(tag)
    - task: Docker@2
      displayName: 'Push the Docker image'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Docker Hub'
        command: 'push sudiptod/image1'
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
